"""Reproduce the pinned EMDN taxonomy JSON without modifying the source workbook.

Standard-library only. Usage: python expert/scripts/import-emdn.py --source <xlsx>
Use --check to compare generated bytes without writing the output.
"""
import argparse
import collections
import hashlib
import json
import pathlib
import re
import xml.etree.ElementTree as ET
import zipfile

EXPECTED_SHA256 = "a973dcdd8ae291248c9d06d355d3cc859d89a5584004db9354721c9c596bc1bd"
NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
HEADERS = ["CATEGORY", "CATEGORY DESCRIPTION (v.2026)", "CODE", "TERM EMDN (v.2026)", "LEVEL", "TERMINAL LEVEL (YES/NO)"]
OFFICIAL_URL = "https://webgate.ec.europa.eu/dyna2/emdn/build/EMDN%20v2026_EN..xlsx"


def read_workbook(source):
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    if digest != EXPECTED_SHA256:
        raise ValueError("Workbook differs from the reviewed 2026 release. Audit the new source before changing the pinned digest.")
    with zipfile.ZipFile(source) as archive:
        strings = ["".join(e.itertext()) for e in ET.fromstring(archive.read("xl/sharedStrings.xml")).findall("m:si", NS)]
        workbook = ET.fromstring(archive.read("xl/workbook.xml"))
        sheets = workbook.findall("m:sheets/m:sheet", NS)
        if len(sheets) != 1 or sheets[0].get("name") != "EMDN_v.2026":
            raise ValueError("Unexpected workbook sheets")
        relationships = {r.get("Id"): r.get("Target") for r in ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))}
        target = relationships[sheets[0].get("{" + REL + "}id")]
        part = target.lstrip("/") if target.startswith("/") else "xl/" + target
        tree = ET.fromstring(archive.read(part))
        rows = []
        for row in tree.findall("m:sheetData/m:row", NS):
            values = {}
            for cell in row.findall("m:c", NS):
                if cell.find("m:f", NS) is not None:
                    raise ValueError("Unexpected formula in classification data")
                value = cell.findtext("m:v", default="", namespaces=NS)
                if cell.get("t") == "s":
                    value = strings[int(value)]
                elif cell.get("t") == "inlineStr":
                    value = "".join(cell.find("m:is", NS).itertext())
                values[re.sub(r"\d", "", cell.get("r"))] = value
            rows.append((int(row.get("r")), values))
    if rows[0][1].get("C") != "EMDN_v.2026" or [rows[1][1].get(c) for c in "ABCDEF"] != HEADERS:
        raise ValueError("Unexpected title or headers")
    data = []
    for number, cells in rows[2:]:
        if any(not cells.get(c) for c in "ABCDEF"):
            raise ValueError(f"Missing value in row {number}")
        data.append({"code": cells["C"], "termRaw": cells["D"], "level": int(cells["E"]), "terminal": cells["F"] == "YES", "row": number})
        if cells["F"] not in ("YES", "NO") or cells["A"] != cells["C"][0]:
            raise ValueError(f"Invalid terminal/category at row {number}")
    codes = {n["code"]: n for n in data}
    if len(codes) != len(data) or len(data) != 8516:
        raise ValueError("Incorrect code count or duplicate code")
    children = collections.Counter(n["code"][:-2] for n in data if n["level"] > 1)
    for node in data:
        code, level = node["code"], node["level"]
        if not re.fullmatch(r"[ABCDFGHJKLMNPQRSTUVWXYZ](?:[0-9]{2}){0,6}", code) or len(code) != 2 * level - 1:
            raise ValueError(f"Invalid code/level: {code}")
        if level > 1 and (code[:-2] not in codes or codes[code[:-2]]["level"] != level - 1):
            raise ValueError(f"Missing/incompatible parent: {code}")
        if node["terminal"] == bool(children[code]):
            raise ValueError(f"Terminal/child conflict: {code}")
    for _, cells in rows[2:]:
        if cells["B"] != codes[cells["A"]]["termRaw"]:
            raise ValueError("Category description differs from root")
    levels = dict(sorted(collections.Counter(n["level"] for n in data).items()))
    software = [n for n in data if re.search(r"\bMEDICAL DEVICE SOFTWARE(?: - NOT INCLUDED IN OTHER CLASSES)?$", n["termRaw"])]
    accessory = [n for n in data if re.search(r"\bSOFTWARE ACCESSOR(?:Y|IES)$", n["termRaw"])]
    counts = {"nodes": len(data), "categories": levels[1], "levels": 7, "byLevel": levels, "terminal": sum(n["terminal"] for n in data), "medicalDeviceSoftware": len(software), "ivdMedicalDeviceSoftware": sum("IVD MEDICAL DEVICE SOFTWARE" in n["termRaw"] for n in software), "softwareAccessories": len(accessory), "duplicateTermLabels": sum(v > 1 for v in collections.Counter(n["termRaw"] for n in data).values()), "parentAfterChildRows": sum(codes[n["code"][:-2]]["row"] > n["row"] for n in data if n["level"] > 1)}
    assert (counts["terminal"], counts["medicalDeviceSoftware"], counts["ivdMedicalDeviceSoftware"], counts["softwareAccessories"]) == (6773, 173, 34, 171)
    return {"schemaVersion": 1, "metadata": {"release": "2026", "language": "en", "declaredVersion": "EMDN_v.2026", "taxonomyVersion": "emdn-2026:" + digest[:16], "workbookSha256": digest, "sourceFilename": "EMDN v2026_EN..xlsx", "sourceSheet": "EMDN_v.2026", "sourceRange": "A3:F8518", "headerRange": "A2:F2", "provenanceStatus": "official-download-byte-match", "officialDownload": {"url": OFFICIAL_URL, "linkedFrom": "https://health.ec.europa.eu/medical-devices-topics-interest/european-medical-devices-nomenclature-emdn_en", "verifiedOn": "2026-10-08", "sha256": EXPECTED_SHA256, "verification": "The supplied workbook bytes matched the official linked download on this date. This is a pinned release, not an automatic current-version check."}, "documentCreated": "2026-01-27T15:20:57Z", "documentModified": "2026-06-17T08:04:06Z", "provenanceNotes": ["Visible title and headers declare v.2026; embedded query field names retain v.3 2025.", "Document timestamps are not release or effective dates.", "No clinician, clinician competency, device risk-class or code-to-specialty mapping is supplied in this taxonomy."], "sourceAnomalies": [{"code": "Z11030482", "range": "C7165:F7165", "note": "Term is INSTRUMENTS FOR RADIOLOGICAL SECTION, despite the suffix shared by software accessories. Original wording is retained; no suffix-based semantic repair."}], "counts": counts}, "nodes": sorted(data, key=lambda n: n["code"])}


def encode(value):
    # Fixed formatting and no execution timestamp make the import byte-reproducible.
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[1] / "data" / "emdn-2026.json")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = encode(read_workbook(args.source))
    if args.source.resolve() == args.output.resolve():
        parser.error("The output cannot replace the source workbook")
    if args.check:
        if not args.output.is_file() or args.output.read_bytes() != payload:
            raise SystemExit("Taxonomy JSON differs from the reproducible source import")
        print("Verified: 8,516 nodes; taxonomy JSON matches the pinned workbook import")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(payload)
        print("Imported: 8,516 nodes from the pinned workbook; source unchanged")
