'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createBriefInterpreter}=require('./brief.cjs');
const {createDeviceInterpreter,validateDeviceContext,validateDeviceDraft,validateClassificationContinuation}=require('./device-context.cjs');
const legacy=require('./device-context-legacy.cjs');
const {restoreBrief}=require('./resume.cjs');
const f=()=>createDeviceInterpreter({interpret:createBriefInterpreter({client:null})});
const update=(action,...codes)=>({classificationUpdate:{action,classifications:codes.map(code=>({system:code.startsWith('MD')?'MDR':'EMDN',code}))}});
const refs=b=>b.deviceContext?.classifications.map(m=>m.key)||[];
const cont=d=>({proposal:d,questionId:d.questionId,questionRevision:d.questionRevision});
const answer=(run,d,message)=>run({previous:d.baseBrief,message,classificationContinuation:cont(d),acceptedBriefVersion:d.baseBriefVersion});

test('MDA0315 asks purpose then subject, applies only latest answer, and commits a typed set',async()=>{
 const seen=[],interpret=createBriefInterpreter({client:null}),run=createDeviceInterpreter({interpret:async i=>{seen.push(i.message);return interpret(i);}}),first=await run({message:'MDA 0315'}),d=first.deviceError.deviceDraft;
 assert.equal(first.clarification.kind,'device-purpose');assert.equal(first.clarification.quickReplies.length,3);assert.ok(validateDeviceDraft(d));
 const second=await answer(run,d,'The software supports diagnosis.'),d2=second.deviceError.deviceDraft;assert.equal(second.clarification.kind,'device-clinical-subject');assert.equal(d2.questionRevision,2);assert.equal(d2.proposalId,d.proposalId);assert.deepEqual(second.brief,d.baseBrief);
 const done=await answer(run,d2,'Coronary artery disease on cardiac CT');assert.equal(done.needsClarification,false);assert.deepEqual(refs(done.brief),['MDR:MDA0315']);assert.ok(done.brief.requirements.some(r=>r.label==='Cardiac CT'));assert.deepEqual(seen,['The software supports diagnosis.','Coronary artery disease on cardiac CT']);assert.ok(validateDeviceContext(done.brief.deviceContext,done.brief.requirements));
});
test('a complete ordinary MDR query requires no extra clarification or role inference',async()=>{const r=await f()({message:'Find specialists for MDA0315 software detecting coronary artery disease on cardiac CT'});assert.equal(r.needsClarification,false);assert.ok(r.brief.requirements.some(x=>x.label==='Cardiac CT'));assert.ok(!r.brief.requirements.some(x=>x.kind==='regulatory'||x.kind==='role'));assert.ok(r.brief.requirements.every(x=>!/MDA0315|stand-alone software/i.test(x.text)));});
test('complementary MDR dimensions retain their exact distinctions and inherit clinical purpose',async()=>{const run=f(),first=await run({message:'MDA0315 + MDS1009 + MDT2010'}),done=await answer(run,first.deviceError.deviceDraft,'Diagnosing coronary artery disease on cardiac CT');assert.equal(done.needsClarification,false);assert.deepEqual(refs(done.brief),['MDR:MDA0315','MDR:MDS1009','MDR:MDT2010']);assert.match(done.notices.join(' '),/cannot establish technical assessor competence/);assert.ok(!done.brief.requirements.some(r=>r.kind==='regulatory'));});
test('technical-assessor competence is an explicit corpus limitation, never a inferred credential',async()=>{const r=await f()({message:'MDS1009. I need a technical assessor'});assert.equal(r.deviceError.code,'device-capability');assert.deepEqual(r.brief.requirements,[]);assert.equal(r.clarification,undefined);});
test('mixed EMDN and MDR references share a clinical focus with both origins and no duplicate criterion',async()=>{const r=await f()({message:'MDA0315 + Z11030692 software diagnosing coronary artery disease on cardiac CT'});assert.equal(r.needsClarification,false);assert.deepEqual(refs(r.brief),['EMDN:Z11030692','MDR:MDA0315']);const ct=r.brief.requirements.filter(x=>x.label==='Cardiac CT');assert.equal(ct.length,1);assert.deepEqual(r.brief.deviceContext.concepts.find(x=>x.requirementId===ct[0].id).origins,['EMDN:Z11030692','MDR:MDA0315']);});
test('whole-set validation rejects unknown, unsupported and conflicting members without mutation',async()=>{const run=f(),first=await run({message:'Dermatologists for Z12040118'}),before=structuredClone(first.brief);for(const input of [{message:'MDA0315 + MDS9999 for detecting skin lesions'},{message:'MDA0315 + IVR0403'},update('add','MDA0315','MDS9999'),{message:'MDA0315',...update('replace','Z12040118')}]){const r=await run({previous:first.brief,...input});assert.ok(r.deviceError);assert.deepEqual(r.brief,before);assert.deepEqual(first.brief,before);}});
test('add/remove/replace preserve explicit user requirements and remove only exhausted code origins',async()=>{const run=f(),first=await run({message:'Dermatologists for Z12040118'}),added=await run({previous:first.brief,...update('add','MDA0315'),message:'Software diagnosing skin lesions using dermoscopy'});assert.equal(added.needsClarification,false);const removed=await run({previous:added.brief,...update('remove','MDA0315')});assert.equal(removed.needsClarification,false);assert.deepEqual(refs(removed.brief),['EMDN:Z12040118']);assert.ok(removed.brief.requirements.some(r=>r.label==='Dermatologist'));assert.ok(removed.brief.deviceContext.concepts.every(c=>!c.origins.includes('MDR:MDA0315')));const clear=await run({previous:removed.brief,...update('clear')});assert.ok(clear.brief.requirements.some(r=>r.label==='Skin-lesion imaging'));assert.ok(clear.brief.requirements.some(r=>r.label==='Dermatologist'));});
test('suppression survives full code clearing, re-add and resume until explicit clinical re-add',async()=>{const run=f(),first=await run({message:'Z12040118'}),id=first.brief.requirements[0].id,removed=await run({previous:first.brief,removeRequirementId:id}),clear=await run({previous:removed.brief,...update('clear')});assert.deepEqual(refs(clear.brief),[]);assert.ok(clear.brief.deviceContext.suppressedConceptKeys.length);const restored=restoreBrief(clear.brief).brief,again=await run({previous:restored,...update('add','Z12040118')});assert.ok(!again.brief.requirements.some(r=>r.id===id));const added=await run({previous:again.brief,message:'Actually include dermoscopy'});assert.ok(added.brief.requirements.some(r=>r.label==='Skin-lesion imaging'));assert.equal(added.brief.deviceContext.suppressedConceptKeys.length,0);assert.equal(added.brief.deviceContext.concepts[0].userOrigin,true);});
test('case, order, duplicate and already-selected addition are idempotent',async()=>{const run=f(),first=await run({message:'MDA0315 + Z11030692 software diagnosing coronary artery disease on cardiac CT'});for(const input of [update('replace','MDA0315','Z11030692','MDA0315'),update('add','Z11030692'),{message:'z11030692 + mda0315'},{}]){const r=await run({previous:first.brief,...input});assert.equal(r.deviceError,undefined);assert.deepEqual(r.brief,first.brief);}});
test('classification proposals reject stale answers, forged metadata and stale question revisions',async()=>{const run=f(),q=await run({message:'MDA0315'}),d=q.deviceError.deviceDraft;for(const changed of [{...cont(d),questionRevision:2},{...cont(d),questionId:'other-question'}]){assert.equal(validateClassificationContinuation(changed),false);const r=await run({message:'Cardiac CT diagnosis',classificationContinuation:changed});assert.equal(r.deviceError.code,'device-conflict');}const stale=await run({previous:{...d.baseBrief,version:1},message:'Cardiac CT diagnosis',classificationContinuation:cont(d)});assert.equal(stale.deviceError.code,'device-conflict');const forged=structuredClone(d);forged.classifications[0].officialTerm='Regulatory-qualified cardiologists';const r=await answer(run,forged,'Cardiac CT diagnosis');assert.ok(['device-conflict','device-version-changed'].includes(r.deviceError.code));});
test('legacy shared flags migrate as uncertain legacy origin rather than asserted explicit user origins',async()=>{for(const message of ['Z12040118','Dermoscopy for Z12040118']){const old=(await legacy.createDeviceInterpreter({interpret:createBriefInterpreter({client:null})})({message})).brief,before=structuredClone(old),run=f(),r=await run({previous:old,message:'Research helpful'});assert.equal(r.deviceError,undefined);assert.ok(r.brief.deviceContext.concepts.every(c=>c.legacyOrigin&&!c.userOrigin));const cleared=await run({previous:r.brief,...update('clear')});assert.ok(cleared.brief.requirements.some(x=>x.label==='Skin-lesion imaging'));assert.deepEqual(old,before);}});
test('different clinical-device code families ask a relationship question instead of assuming separate devices',async()=>{const run=f(),r=await run({message:'Z12040118 + J010792'});assert.equal(r.deviceError.code,'device-clarification');assert.equal(r.clarification.kind,'device-relationship');const done=await answer(run,r.deviceError.deviceDraft,'One combined device with a shared clinical purpose');assert.equal(done.deviceError,undefined);assert.equal(refs(done.brief).length,2);});

test('explicit shared clinical purpose can combine general CT and dermoscopy without inventing cardiac expertise',async()=>{const run=f(),first=await run({message:'Z11030692 + Z12040118'}),done=await answer(run,first.deviceError.deviceDraft,'One device with a shared clinical purpose, diagnosing skin lesions with general CT and dermoscopy.');assert.equal(done.deviceError,undefined);assert.ok(done.brief.requirements.some(r=>r.label==='CT imaging'));assert.ok(done.brief.requirements.some(r=>r.label==='Skin-lesion imaging'));assert.ok(!done.brief.requirements.some(r=>r.label==='Cardiac CT'));assert.equal(done.brief.deviceContext.relationship.kind,'shared-purpose');});

test('compatible broad software codes share purpose and subject with exactly two questions',async()=>{const run=f(),first=await run({message:'V92 + MDA0315'});assert.equal(first.clarification.kind,'device-purpose');const second=await answer(run,first.deviceError.deviceDraft,'The software supports diagnosis.');assert.equal(second.clarification.kind,'device-clinical-subject');const done=await answer(run,second.deviceError.deviceDraft,'Coronary artery disease on cardiac CT');assert.equal(done.deviceError,undefined);assert.equal(done.needsClarification,false);assert.deepEqual(refs(done.brief),['EMDN:V92','MDR:MDA0315']);assert.equal(done.brief.requirements.filter(r=>r.label==='Cardiac CT').length,1);assert.ok(done.brief.deviceContext.concepts.find(c=>c.requirementId===done.brief.requirements.find(r=>r.label==='Cardiac CT').id).origins.includes('MDR:MDA0315'));assert.deepEqual(second.deviceError.deviceDraft.answers.map(a=>a.classificationKey),['EMDN:V92']);});

test('software lifecycle and manufacturing assessors receive the capability limitation across code families',async()=>{const run=f(),previous=(await run({message:'Cardiologists'})).brief;for(const message of ['Find software lifecycle assessors for MDA0315','Find software life-cycle auditors for V92','Find manufacturing auditors for Z12040118','Find assessors for software lifecycle','Find technical assessors']){const r=await run({previous,message});assert.equal(r.deviceError?.code,'device-capability',message);assert.equal(r.clarification,undefined,message);assert.deepEqual(r.brief,previous,message);}});
test('clinical experts for software remain eligible without implying technical assessor competence',async()=>{for(const message of ['Clinical experts for MDA0315 software diagnosing coronary artery disease on cardiac CT','Clinical experts for software diagnosing coronary artery disease']){const r=await f()({message});assert.equal(r.deviceError,undefined,message);assert.equal(r.needsClarification,false,message);assert.ok(r.brief.requirements.some(x=>x.label==='Coronary artery disease'),message);}});

test('an explicitly negated technical-assessor request is not mislabelled as a capability request',async()=>{const r=await f()({message:'Clinical experts for MDA0315 software diagnosing coronary artery disease; not software lifecycle assessors'});assert.notEqual(r.deviceError?.code,'device-capability');assert.equal(r.interpretationIncomplete,true,'The unresolved negative instruction stays with ordinary interpretation recovery');});

test('separate and negated-shared relationship answers never combine devices or loop',async()=>{const run=f(),previous=(await run({message:'Cardiologists'})).brief,first=await run({previous,message:'Z12040118 + J010792'});assert.equal(first.clarification.kind,'device-relationship');for(const message of ['They are not the same device.','These are separate devices, not one shared purpose.','Separate devices.','They are different devices.','They aren’t the same device.','One shared purpose is not established; these are separate devices.']){const r=await answer(run,first.deviceError.deviceDraft,message);assert.equal(r.deviceError?.code,'device-conflict',message);assert.match(r.deviceError.error,/separate projects/i,message);assert.equal(r.clarification,undefined,message);assert.deepEqual(r.brief,previous,message);assert.equal(r.brief.deviceContext,undefined,message);}});
test('a negated separation followed by explicit shared-device intent remains usable',async()=>{const run=f(),first=await run({message:'Z12040118 + J010792'}),r=await answer(run,first.deviceError.deviceDraft,'They are not separate devices, but one combined device with a shared clinical purpose.');assert.equal(r.deviceError,undefined);assert.equal(r.brief.deviceContext.relationship.kind,'shared-purpose');assert.ok(validateDeviceContext(r.brief.deviceContext,r.brief.requirements));});
