'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const E=require('./extraction.cjs');
const source={id:'source-one',candidateId:'expert-one',sourceRecordId:'record-one',field:'about',text:'I interpret cardiac CT scans in adults in a specialist clinic. In 2018 I completed a research study.',textKind:'verbatim',sourceUrl:'https://example.org/profile',sourceLabel:'Professional profile',dates:{sourceDate:null,observedAt:'2026-10-06'},qualifiers:['reported-activity-not-current-verification'],limitations:['The undated profile does not establish current practice.']};
const claim=()=>({source:'s1',quote:'I interpret cardiac CT scans in adults in a specialist clinic.',kind:'clinical-activity',subject:'professional',activity:['interpret'],modality:['cardiac CT'],condition:[],population:['adults'],setting:['specialist clinic'],dates:[]});
function wire(){return {claims:[claim()]};}
function clientFor(value=wire()){const calls=[];return {calls,chat:{completions:{create:async(...args)=>{calls.push(args);return {choices:[{finish_reason:'stop',message:{content:JSON.stringify(typeof value==='function'?value():value)}}]};}}}};}
async function harness(t,value=wire()){const cacheDir=await fs.mkdtemp(path.join(os.tmpdir(),'docmap-extraction-test-'));t.after(async()=>{assert.equal(path.dirname(path.resolve(cacheDir)),path.resolve(os.tmpdir()));assert.ok(path.basename(cacheDir).startsWith('docmap-extraction-test-'));await fs.rm(cacheDir,{recursive:true,force:true});});const client=clientFor(value);return {cacheDir,client,run:E.createExtractor({client,cacheDir})};}
const review={actor:'user',decision:'accept',reviewer:'Fixture source reviewer',identityChecked:true,sourceChecked:true,subjectChecked:true,identityBasis:'Source profile and existing professional record were checked.',method:'public-page-review',observedAt:'2026-10-06',type:'clinical-practice',limitations:['Engagement availability and current scope require direct confirmation.']};

test('extractor is offline by default and does not create a proposal cache without a model result',async t=>{const h=await harness(t);const result=await h.run({sources:[source]});assert.equal(result.status,'not-run');assert.equal(h.client.calls.length,0);assert.deepEqual(await fs.readdir(h.cacheDir),[]);});
test('bounded extraction defaults to DeepSeek with strict schema and proposal-only output',async t=>{const h=await harness(t),result=await h.run({sources:[source],live:true}),[request,options]=h.client.calls[0];assert.equal(request.model,E.DEFAULT_MODEL);assert.equal(request.response_format.json_schema.strict,true);assert.equal(request.response_format.json_schema.schema.additionalProperties,false);assert.equal(options.timeout,15000);assert.equal(result.status,'proposals-only');assert.equal(result.proposals[0].reviewState,'proposal-requires-source-review');assert.equal(result.proposals[0].candidateId,source.candidateId);assert.equal(result.proposals[0].sourceRecordId,source.sourceRecordId);assert.equal(result.proposals[0].verified,undefined);});
test('wire input strips private notes, recruitment events, status and identity fields',async t=>{const h=await harness(t);await h.run({sources:[{...source,notes:'PRIVATE NOTE',events:[{detail:'PRIVATE EVENT'}],qualification:'approved',name:'PRIVATE NAME'}],live:true});const sent=JSON.stringify(h.client.calls[0][0].messages);for(const value of ['PRIVATE NOTE','PRIVATE EVENT','PRIVATE NAME',source.candidateId,source.sourceRecordId])assert.equal(sent.includes(value),false);assert.ok(sent.includes(source.limitations[0]));});
test('identical source/model/version reuses validated disk proposals without another paid call',async t=>{const h=await harness(t),first=await h.run({sources:[source],live:true});const second=await E.createExtractor({client:h.client,cacheDir:h.cacheDir})({sources:[source]});assert.equal(h.client.calls.length,1);assert.equal(second.cacheHit,true);assert.deepEqual(second.proposals,first.proposals);});
test('source content, dates, attribution, model and extractor version invalidate the cache key',()=>{const first=E.manifest([source]);for(const changed of [{...source,text:source.text+' Another sentence.'},{...source,sourceRecordId:'corrected-record'},{...source,candidateId:'corrected-identity'},{...source,sourceUrl:'https://example.org/corrected'},{...source,dates:{...source.dates,observedAt:'2026-10-07'}},{...source,limitations:['New scope limitation.']}])assert.notEqual(E.manifest([changed]).cacheKey,first.cacheKey);assert.notEqual(E.manifest([source],{model:'deepseek/another-version'}).cacheKey,first.cacheKey);assert.notEqual(E.manifest([source],{version:'v2'}).cacheKey,first.cacheKey);});
test('simultaneous identical jobs share one model request',async t=>{const h=await harness(t);await Promise.all([h.run({sources:[source],live:true}),h.run({sources:[source],live:true})]);assert.equal(h.client.calls.length,1);});
test('cached derived identities are rebuilt from canonical source input',async t=>{const h=await harness(t),first=await h.run({sources:[source],live:true}),file=path.join(h.cacheDir,first.cacheKey+'.json'),tampered=JSON.parse(await fs.readFile(file));tampered.proposals[0].candidateId='wrong-person';await fs.writeFile(file,JSON.stringify(tampered));assert.equal((await h.run({sources:[source]})).proposals[0].candidateId,source.candidateId);});
test('corrupt cached source spans fail closed without another model request',async t=>{const h=await harness(t),first=await h.run({sources:[source],live:true}),file=path.join(h.cacheDir,first.cacheKey+'.json'),tampered=JSON.parse(await fs.readFile(file));tampered.wire.claims[0].quote='Invented experience';await fs.writeFile(file,JSON.stringify(tampered));await assert.rejects(h.run({sources:[source],live:true}),/cached extraction is invalid/);assert.equal(h.client.calls.length,1);});
for(const [name,mutate]of [['unknown source',c=>c.source='s8'],['invented quote',c=>c.quote='Reports dermoscopy.'],['wrong offset',c=>c.start=1],['invented attribute',c=>c.population=['children']],['status injection',c=>c.qualification='approved'],['identity injection',c=>c.candidateId='other'],['unrecognized kind',c=>c.kind='verified-current-practice']])test(name+' is rejected before proposals can be stored',()=>{const w=wire();mutate(w.claims[0]);assert.throws(()=>E.validateWire(w,E.prepareSources([source])));});
test('duplicate proposals are rejected and empty extraction is an honest result',()=>{const w=wire();w.claims.push({...w.claims[0]});assert.throws(()=>E.validateWire(w,E.prepareSources([source])),/Duplicate/);assert.deepEqual(E.validateWire({claims:[]},E.prepareSources([source])),[]);});
test('server derives exact UTF-16 spans without asking the model to count characters',()=>{const changed={...source,text:'🔬\n'+source.text},result=E.validateWire(wire(),E.prepareSources([changed]));assert.equal(result[0].start,3);assert.equal(result[0].end,3+claim().quote.length);assert.equal(changed.text.slice(result[0].start,result[0].end),claim().quote);});
test('repeated exact quotes are ambiguous and never fuzzily repaired',()=>{const changed={...source,text:source.text+' '+claim().quote};assert.throws(()=>E.validateWire(wire(),E.prepareSources([changed])),error=>error.diagnostics?.reason==='literal-quote-is-ambiguous');const w=wire();w.claims[0].quote=w.claims[0].quote.replace('CT','ct');assert.throws(()=>E.validateWire(w,E.prepareSources([source])),error=>error.diagnostics?.reason==='literal-quote-not-found');});
test('optional caller-supplied offsets are validation-only and cannot disambiguate an unsafe quote',()=>{const w=wire();Object.assign(w.claims[0],{start:0,end:claim().quote.length});assert.equal(E.validateWire(w,E.prepareSources([source]))[0].start,0);w.claims[0].end--;assert.throws(()=>E.validateWire(w,E.prepareSources([source])),error=>error.diagnostics?.reason==='supplied-offsets-disagree');});
test('quote rejection diagnostics contain only reason and lengths, never source text or identities',()=>{const w=wire();w.claims[0].quote='Invented evidence not in this source';try{E.validateWire(w,E.prepareSources([source]));assert.fail();}catch(error){assert.deepEqual(Object.keys(error.diagnostics).sort(),['quoteCharacters','reason','sourceCharacters']);for(const value of [source.text,source.candidateId,source.sourceRecordId,w.claims[0].quote])assert.equal(JSON.stringify(error.diagnostics).includes(value),false);}});
test('received paraphrases and oversized jobs cannot masquerade as bounded literal sources',()=>{assert.throws(()=>E.prepareSources([{...source,reviewedParaphrase:true}]),/verbatim/);assert.throws(()=>E.prepareSources([{...source,textKind:'summary'}]),/verbatim/);assert.throws(()=>E.prepareSources(Array.from({length:9},(_,i)=>({...source,id:'id-'+i}))),/one to eight/);assert.throws(()=>E.prepareSources([{...source,text:'x'.repeat(5001)}]),/bounded text/);assert.throws(()=>E.prepareSources([{...source,sourceUrl:'https://user:secret@example.org'}]),/credentials/);assert.throws(()=>E.prepareSources([{...source,limitations:Array(21).fill('limitation')}]),/complete bounded/);});
test('review acceptance requires deliberate identity, source and subject checks; never AI decisions',async t=>{const h=await harness(t),job=await h.run({sources:[source],live:true}),id=job.proposals[0].id;for(const overrides of [{actor:'ai'},{identityChecked:false},{sourceChecked:false},{subjectChecked:false},{limitations:[]},{method:'copied-record'},{type:'approved-assessor'}])assert.throws(()=>E.reviewProposal(job,id,{...review,...overrides,sources:[source]}));});
test('accepted enrichment preserves literal proof, source limits and extraction provenance without live publication',async t=>{const h=await harness(t),job=await h.run({sources:[source],live:true}),accepted=E.reviewProposal(job,job.proposals[0].id,{...review,sources:[source]});assert.equal(accepted.verified,true);assert.equal(accepted.excerpt,wire().claims[0].quote);assert.equal(accepted.sourceRecordId,source.sourceRecordId);assert.equal(accepted.candidateId,source.candidateId);assert.equal(accepted.review.extraction.cacheKey,job.cacheKey);assert.deepEqual(accepted.review.extraction.attributes.population,['adults']);assert.ok(accepted.review.limitations.includes(source.limitations[0]));assert.equal(accepted.qualification,undefined);assert.equal(accepted.currentPractice,undefined);assert.equal(job.proposals[0].reviewState,'proposal-requires-source-review');});
test('source changes invalidate review and do not apply an old proposal to corrected evidence',async t=>{const h=await harness(t),job=await h.run({sources:[source],live:true});assert.throws(()=>E.reviewProposal(job,job.proposals[0].id,{...review,sources:[{...source,text:source.text+' Corrected.'}]}),/changed/);});
test('received training and study context cannot be promoted to personal performed clinical activity',async t=>{for(const changes of [{kind:'received-training'},{subject:'study'},{subject:'unclear'}]){const w=wire();Object.assign(w.claims[0],changes);const h=await harness(t,w),job=await h.run({sources:[source],live:true});assert.throws(()=>E.reviewProposal(job,job.proposals[0].id,{...review,sources:[source]}));}});
test('reviewed enrichment cannot assert current practice, assessor approval or independence',async t=>{const h=await harness(t),job=await h.run({sources:[source],live:true});for(const summary of ['This is an approved assessor.','The professional is conflict-free.','The clinician currently practises.'])assert.throws(()=>E.reviewProposal(job,job.proposals[0].id,{...review,sources:[source],summary}),/cannot establish/);});
test('transport failures cache nothing and do not echo provider credential errors',async t=>{const h=await harness(t);h.client.chat.completions.create=async()=>{throw Error('PRIVATE_CREDENTIAL_DIAGNOSTIC');};await assert.rejects(h.run({sources:[source],live:true}),error=>!error.message.includes('PRIVATE_CREDENTIAL_DIAGNOSTIC'));assert.deepEqual(await fs.readdir(h.cacheDir),[]);});
test('incomplete model completion is rejected even when the visible JSON looks valid',async t=>{const h=await harness(t);h.client.chat.completions.create=async()=>({choices:[{finish_reason:'length',message:{content:JSON.stringify(wire())}}]});await assert.rejects(h.run({sources:[source],live:true}),/did not complete/);assert.deepEqual(await fs.readdir(h.cacheDir),[]);});
