'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),P=require('./public/projects.js');
const classification=(system,code)=>({key:system+':'+code,system,code,family:system==='MDR'?code.slice(0,3):'EMDN',officialTerm:'Synthetic official term '+code,release:'test-release',taxonomyVersion:'taxonomy-v1',taxonomyDigest:'a'.repeat(64),mappingVersion:'mapping-v1',sourceUrl:'https://example.com/official',hierarchy:[{code,term:'Synthetic hierarchy'}]});
const context=()=>({schemaVersion:2,classifications:[classification('MDR','MDA0315'),classification('MDR','MDS1009'),classification('EMDN','Z11030692')],concepts:[{key:'cardiac-ct',requirementId:'ct',state:'active',origins:['MDR:MDA0315','EMDN:Z11030692'],userOrigin:false,legacyOrigin:false}],suppressedConceptKeys:[],interpretation:'Related cardiac CT expertise.',derivedRequirementIds:['ct'],clinicalPurpose:[{classificationKey:'MDR:MDA0315',text:'Cardiac CT'}]});
const brief=()=>({version:1,summary:'Cardiac CT',requirements:[{id:'ct',kind:'modality',label:'Cardiac CT',text:'Cardiac CT',importance:'focus'}],deviceContext:context()});
const candidate={id:'expert-a',name:'Dr A',reasons:[],requirementMatrix:[],evidence:[]};
const saved=()=>P.changeReview(P.saveCandidate(P.createProject('Classification set'),candidate,brief(),'corpus-v1'),candidate.id,'qualification','reviewed-by-team',{actor:'user'});
const draft=()=>({schemaVersion:2,proposalId:'proposal-1',baseBriefVersion:1,baseBrief:brief(),proposedBrief:brief(),classifications:context().classifications,clinicalText:'A fictional clinical software request',answers:[],question:'What will it be used for?',questionId:'question-1',questionRevision:1,questionKind:'device-purpose',questionClassificationKey:'MDR:MDA0315'});
const pending=()=>({id:'pending-1',kind:'device-purpose',question:'What will it be used for?',quickReplies:[{id:'ct',message:'Cardiac CT'}],submittedAt:'2026-10-08',payload:{message:'MDA0315',requestId:'request-1',acceptedBriefVersion:1},baseBrief:brief(),proposedBrief:null,deviceDraft:draft(),filters:{documentedOnly:false,uncontactedOnly:false},visibleRequest:'MDA0315'});

test('versioned code sets retain schema-one projects and frozen evidence through backup',()=>{const p=saved(),restored=P.importJSON(P.exportJSON(p));assert.equal(restored.schema,1);assert.deepEqual(restored.activeBrief.deviceContext,p.activeBrief.deviceContext);assert.deepEqual(restored.candidates,p.candidates);assert.equal(restored.candidates[0].needsReview,false);});
test('set scope ignores order, code casing and generated interpretation while retaining meaningful origins and versions',()=>{
  const p=saved(),b=brief(),d=b.deviceContext;d.classifications.reverse();for(const c of d.classifications){c.key=c.key.toLowerCase();c.system=c.system.toLowerCase();c.code=c.code.toLowerCase();c.family=c.family.toLowerCase();}d.concepts[0].origins=d.concepts[0].origins.reverse().map(x=>x.toLowerCase());d.clinicalPurpose[0].classificationKey=d.clinicalPurpose[0].classificationKey.toLowerCase();d.interpretation='Same search, rewritten presentation.';
  assert.equal(P.scope(p.activeBrief),P.scope(b));assert.throws(()=>P.validateProject({...p,activeBrief:b}),/device context/);assert.equal(P.setBrief(p,b,'corpus-v1').candidates[0].needsReview,false);
  for(const mutate of [d=>d.classifications[0].mappingVersion='mapping-v2',d=>d.classifications[0].taxonomyDigest='b'.repeat(64),d=>d.concepts[0].userOrigin=true,d=>d.suppressedConceptKeys.push('other-modality')]){const changed=brief();mutate(changed.deviceContext);assert.equal(P.setBrief(p,changed,'corpus-v1').candidates[0].needsReview,true);assert.deepEqual(p.candidates[0].brief,brief());}
});
test('empty selected-code set can retain suppression without appearing as a current classification',()=>{const p=saved(),b=brief();b.deviceContext={schemaVersion:2,classifications:[],concepts:[],suppressedConceptKeys:['cardiac-ct'],interpretation:'',derivedRequirementIds:[],clinicalPurpose:[]};const next=P.setBrief(p,b,'corpus-v1');assert.deepEqual(P.importJSON(P.exportJSON(next)).activeBrief.deviceContext,b.deviceContext);assert.equal(next.candidates[0].needsReview,true);const fresh=P.setBrief(P.createProject(),b,'corpus-v1');assert.doesNotMatch(P.exportHTML(fresh),/<h3>Device classifications/);});
test('structured proposals and exact bound continuation survive reload without modifying accepted work',()=>{const p=P.setPendingClarification(saved(),pending()),q=p.pendingClarification;const continuation={proposal:q.deviceDraft,questionId:q.deviceDraft.questionId,questionRevision:q.deviceDraft.questionRevision};p.failedSearch={id:'answer-1',status:'failed',submittedAt:'2026-10-08',payload:{message:'Cardiac CT',classificationContinuation:continuation,requestId:'answer-1',acceptedBriefVersion:1},baseBrief:brief(),filters:q.filters};p.draft='Separate unsent text';const restored=P.importJSON(P.exportJSON(p));assert.deepEqual(restored.pendingClarification,q);assert.deepEqual(restored.failedSearch,p.failedSearch);assert.equal(restored.draft,p.draft);assert.equal(restored.candidates[0].needsReview,false);assert.deepEqual(P.clearPendingClarification(restored).activeBrief,p.activeBrief);});
test('set validators reject duplicate codes, wrong origins, unsupported lineage and malformed pending revisions',()=>{
  for(const alter of [d=>d.classifications.push({...d.classifications[0],code:'mda0315',key:'mdr:mda0315'}),d=>d.classifications[0].system='IVDR',d=>d.classifications[0].family='MDS',d=>d.classifications[0].sourceUrl='javascript:alert(1)',d=>d.concepts[0].origins=['MDR:MDA9999'],d=>d.concepts[0].userOrigin='yes',d=>d.derivedRequirementIds=['other'],d=>d.clinicalPurpose[0].classificationKey='MDR:MDA9999']){const p=saved();alter(p.activeBrief.deviceContext);assert.throws(()=>P.validateProject(p),/device context/);}
  for(const alter of [q=>q.deviceDraft.questionRevision=0,q=>q.deviceDraft.baseBriefVersion=2,q=>q.deviceDraft.classifications='not an array',q=>q.deviceDraft.answers=[{classificationKey:'MDR:MDA9999',kind:'device-purpose',message:'Cardiac CT'}],q=>q.payload.classificationContinuation={proposal:draft(),questionId:'wrong',questionRevision:1},q=>q.payload.classificationUpdate={action:'delete',classifications:[]},q=>q.payload.acceptedBriefVersion=-1]){const q=pending();alter(q);assert.throws(()=>P.setPendingClarification(saved(),q),/invalid/);}
});
test('review pack groups official definitions and links without blending classification into professional evidence',()=>{const p=saved();p.activeBrief.deviceContext.classifications.push(classification('MDR','MDT2001'));p.activeBrief.deviceContext.classifications[0].officialTerm='<script>not markup</script>';const html=P.exportHTML(p);for(const heading of ['Device type','Characteristics','Technologies and processes','EMDN'])assert.ok(html.includes('<h4>'+heading+'</h4>'));assert.match(html,/Official classification reference/);assert.match(html,/&lt;script&gt;not markup/);assert.doesNotMatch(html,/<script>/);assert.match(html,/not evidence of a professional/);assert.match(html,/mapping-v1/);});
test('explicit shared-purpose context is preserved as user input, contributes to scope and is escaped in exports',()=>{const p=saved(),b=brief();b.deviceContext.relationship={kind:'shared-purpose',text:'One device for a shared <clinical> purpose.'};const next=P.setBrief(p,b,'corpus-v1');assert.equal(next.candidates[0].needsReview,true);assert.deepEqual(P.importJSON(P.exportJSON(next)).activeBrief.deviceContext.relationship,b.deviceContext.relationship);const html=P.exportHTML(next);assert.match(html,/Shared purpose described by the user/);assert.match(html,/shared &lt;clinical&gt; purpose/);assert.equal(next.candidates[0].brief.deviceContext.relationship,undefined);b.deviceContext.relationship.kind='approved';assert.throws(()=>P.validateProject({...p,activeBrief:b}),/device context/);});
