'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {restoreBrief}=require('./resume.cjs'),{parseBrief}=require('./brief.cjs');
const {createApp}=require('./server.cjs');
const example=()=>parseBrief({message:'Find only cardiologists, exclude radiologists, for adult cardiac CT in the UK. Diagnostic research preferred. Manufacturer: Example Medical; panel of 3 experts; within 2 weeks.'}).brief;
test('resume preserves complete active intent and version without reinterpreting a summary',()=>{const before=example(),after=restoreBrief(before);assert.deepEqual(after.brief,before);assert.equal(after.mode,'saved-brief');assert.equal(after.needsClarification,false);});
test('legacy brief-level only-role restrictions cannot silently broaden on resume',()=>{const before=parseBrief({message:'Only general practitioners for skin lesion imaging'}).brief;for(const r of before.requirements)delete r.strictRole;const after=restoreBrief(before).brief;assert.equal(after.roleMode,'only');assert.deepEqual(after.roles,before.roles);assert.equal(after.version,before.version);});
test('resume rejects notes, status claims, evidence and prototype fields at either boundary',()=>{for(const patch of [{notes:'Private'},{candidates:[]},{approved:true},{__proto__:null,constructor:'unsafe'}])assert.throws(()=>restoreBrief({...example(),...patch}));for(const patch of [{sourceUrl:'https://example.org'},{status:'approved'},{evidenceIds:['foreign']}]){const b=example();Object.assign(b.requirements[0],patch);assert.throws(()=>restoreBrief(b));}});
test('resume rejects duplicate IDs, excessive sizes and malformed role constraints',()=>{for(const mutate of [b=>b.requirements.push(b.requirements[0]),b=>b.requirements[0].text='x'.repeat(4001),b=>b.requirements[0].importance='approved',b=>b.requirements.find(r=>r.kind==='modality').polarity='exclude',b=>b.version=-1,b=>b.panelSize=1000]){const b=example();mutate(b);assert.throws(()=>restoreBrief(b));}});
async function api(t){let parsed=0,ranked=0,received;const engine={ready:true,search:async brief=>{ranked++;received=structuredClone(brief);return{results:[{id:'from-server',evidence:[]}],corpusVersion:'current-v2'};}};const app=createApp(engine,{interpret:async input=>{parsed++;return parseBrief(input);}}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));return {get counts(){return{parsed,ranked};},get received(){return received;},post:async body=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/expert/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()};}};}
test('reload resumes the saved brief against fresh authoritative evidence without model use',async t=>{const h=await api(t),b=example(),r=await h.post({resumeBrief:b});assert.equal(r.status,200);assert.equal(r.body.interpretationMode,'saved-brief');assert.deepEqual(r.body.brief,b);assert.deepEqual(h.counts,{parsed:0,ranked:1});assert.equal(r.body.corpusVersion,'current-v2');assert.equal(r.body.results[0].id,'from-server');assert(r.body.sessionId&&r.body.searchId);});
test('a failed refinement can retry after reload using its base brief in a single search',async t=>{const h=await api(t),b=example(),id=b.requirements.find(r=>r.kind==='population').id,r=await h.post({resumeBrief:b,patch:{requirementId:id,importance:'preferred'}});assert.equal(r.status,200);assert.equal(r.body.brief.requirements.find(r=>r.id===id).importance,'preferred');assert.equal(r.body.brief.manufacturer,b.manufacturer);assert.equal(r.body.brief.version,b.version+1);assert.deepEqual(h.counts,{parsed:1,ranked:1});});
test('resume rejects conflicting session/operations before retrieval',async t=>{const h=await api(t);for(const body of [{resumeBrief:example(),sessionId:'another'},{resumeBrief:example(),message:'Adults preferred',removeRequirementId:'r-one'},{resumeBrief:example(),notes:'Not for server'}])assert.equal((await h.post(body)).status,400);assert.deepEqual(h.counts,{parsed:0,ranked:0});});
test('resuming an incomplete brief clarifies without fabricating candidates',async t=>{const h=await api(t),b={...example(),requirements:[]},r=await h.post({resumeBrief:b});assert.equal(r.status,200);assert.equal(r.body.needsClarification,true);assert.equal(h.counts.ranked,0);});
