'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createApp}=require('./server.cjs');
const {parseBrief}=require('./brief.cjs');
const evidence={id:'e1',candidateId:'a',text:'Reports cardiac CT.',sourceRecordId:'r1',field:'about',type:'clinical-practice',dates:{},sourceUrl:'https://example.org/a'};
async function harness(t,options={}){let searches=0,generations=0;const results=Array.from({length:14},(_,i)=>({id:i?'c'+i:'a',name:'Person '+i,evidence:[{...evidence,candidateId:i?'c'+i:'a'}],requirementMatrix:[],questions:[],reasons:[],gaps:[]}));const engine={ready:true,status:'Ready',corpus:{version:'v1',candidates:results,passages:[evidence]},search:async brief=>{searches++;if(options.failSearch)throw Error('failure');return{brief,results,corpusVersion:'v1'};}};const app=createApp(engine,{interpret:async input=>parseBrief(input),generate:async input=>{generations++;return {provider:'deepseek',sections:input.candidates.map(c=>({candidateId:c.id,text:c.evidence[0].text,evidenceIds:['e1']})),retryable:false};},...options});const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const base='http://127.0.0.1:'+server.address().port;const post=async(endpoint,body,headers={})=>{const r=await fetch(base+'/api/expert/'+endpoint,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});return{status:r.status,body:await r.json()};};const start=()=>post('search',{message:'Cardiac CT for coronary artery disease'});return {base,post,start,engine,counts:()=>({searches,generations})};}
test('expert route and health are isolated from patient search APIs',async t=>{const h=await harness(t);assert.equal((await fetch(h.base+'/api/health')).status,200);assert.equal((await fetch(h.base+'/api/search',{method:'POST'})).status,404);});
test('underspecified input asks clarification without ranking',async t=>{const h=await harness(t),r=await h.post('search',{message:'Find an expert'});assert.equal(r.body.needsClarification,true);assert.equal(h.counts().searches,0);});
test('pagination shares snapshot and cannot trigger retrieval',async t=>{const h=await harness(t),first=await h.start(),next=await h.post('page',{sessionId:first.body.sessionId,searchId:first.body.searchId,cursor:first.body.nextCursor});assert.equal(first.body.results.length,6);assert.equal(next.body.results.length,6);assert.equal(next.body.results[0].id,'c6');assert.equal(h.counts().searches,1);});
test('pagination cursor is stable on retry',async t=>{const h=await harness(t),first=(await h.start()).body,request={sessionId:first.sessionId,searchId:first.searchId,cursor:first.nextCursor};assert.deepEqual((await h.post('page',request)).body,(await h.post('page',request)).body);});
test('malformed model requests fail without paid generation',async t=>{const h=await harness(t),s=(await h.start()).body;for(const candidateIds of [{id:'a'},'a',null,42])assert.equal((await h.post('explain',{sessionId:s.sessionId,searchId:s.searchId,candidateIds})).status,400);assert.equal(h.counts().generations,0);});
test('client cannot submit replacement evidence or credentials',async t=>{const h=await harness(t),s=(await h.start()).body;assert.equal((await h.post('explain',{sessionId:s.sessionId,searchId:s.searchId,candidateIds:['a'],evidence:[{text:'Approved'}]})).status,400);assert.equal((await h.post('search',{message:'Cardiac CT',status:'approved'})).status,400);});
test('wrong candidate is rejected before model generation',async t=>{const h=await harness(t),s=(await h.start()).body;assert.equal((await h.post('explain',{sessionId:s.sessionId,searchId:s.searchId,candidateIds:['other']})).status,404);assert.equal(h.counts().generations,0);});
test('verified explanation is cached against exact snapshot',async t=>{const h=await harness(t),s=(await h.start()).body,request={sessionId:s.sessionId,searchId:s.searchId,candidateIds:['a']};await h.post('explain',request);await h.post('explain',request);assert.equal(h.counts().generations,1);const n=(await h.post('search',{sessionId:s.sessionId,message:'Adults preferred'})).body;await h.post('explain',{...request,searchId:n.searchId});assert.equal(h.counts().generations,2);});
test('comparison requires two or three snapshot candidates',async t=>{const h=await harness(t),s=(await h.start()).body;for(const candidateIds of [['a'],['a','c1','c2','c3']])assert.equal((await h.post('explain',{sessionId:s.sessionId,searchId:s.searchId,kind:'comparison',candidateIds})).status,400);});
test('refinement preserves and explicitly removes criteria',async t=>{const h=await harness(t),s=(await h.start()).body,id=s.brief.requirements.find(r=>r.kind==='condition').id;const n=(await h.post('search',{sessionId:s.sessionId,removeRequirementId:id})).body;assert.ok(n.brief.requirements.some(r=>r.kind==='modality'));assert.ok(!n.brief.requirements.some(r=>r.id===id));});
test('project contact filtering only uses explicitly supplied IDs',async t=>{const h=await harness(t),s=(await h.post('search',{message:'Cardiac CT',excludeContactedIds:['a']})).body;assert.equal(s.total,13);assert.ok(!s.results.some(c=>c.id==='a'));assert.equal((await h.start()).body.total,14);});
test('origin guard refuses cross-site requests',async t=>{const h=await harness(t);assert.equal((await h.post('search',{message:'Cardiac CT'},{origin:'https://unrelated.example'})).status,403);});
test('failed retrieval keeps previous brief and allows retry',async t=>{const h=await harness(t),s=(await h.start()).body,original=h.engine.search;h.engine.search=async()=>{throw Error('test');};assert.equal((await h.post('search',{sessionId:s.sessionId,message:'Primary care essential'})).status,500);h.engine.search=original;const n=(await h.post('search',{sessionId:s.sessionId,message:'Adults preferred'})).body;assert.ok(!n.brief.requirements.some(r=>r.label==='Primary care'));});
test('source pages escape HTML and do not expose raw cache',async t=>{const h=await harness(t);h.engine.corpus.passages[0]={...evidence,text:'<script>doBad()</script>',sourceUrl:'javascript:doBad()'};const r=await fetch(h.base+'/api/expert/sources/a'),text=await r.text();assert.ok(text.includes('&lt;script&gt;'));assert.ok(!text.includes('href="javascript:'));assert.equal((await fetch(h.base+'/expert-assets/../.cache/raw.json')).status,404);});

test('source pages retain full escaped source-review limitations',async t=>{const h=await harness(t);const limitation='Historical coauthorship does not establish a specific investigator task. <script>no()</script>';h.engine.corpus.passages[0]={...evidence,review:{limitations:[limitation]}};const text=await(await fetch(h.base+'/api/expert/sources/a')).text();assert(text.includes('Historical coauthorship does not establish a specific investigator task. &lt;script&gt;no()&lt;/script&gt;'));assert(!text.includes('<script>no()'));});

test('simple discovery reaches retrieval and a focus priority patch preserves interest intent',async t=>{
  const h=await harness(t),first=await h.post('search',{message:'Cardiologists with radiology interests'});
  assert.equal(first.status,200);assert.equal(first.body.needsClarification,false);assert.equal(h.counts().searches,1);
  const imaging=first.body.brief.requirements.find(r=>r.label==='Medical imaging');
  assert.equal(imaging.importance,'focus');assert.equal(imaging.matchIntent,'interest');
  const required=await h.post('search',{sessionId:first.body.sessionId,patch:{requirementId:imaging.id,importance:'essential'}});
  assert.equal(required.body.brief.requirements.find(r=>r.id===imaging.id).importance,'essential');
  const focus=await h.post('search',{sessionId:first.body.sessionId,patch:{requirementId:imaging.id,importance:'focus'}});
  assert.equal(focus.status,200);assert.equal(focus.body.brief.requirements.find(r=>r.id===imaging.id).importance,'focus');
  assert.equal(focus.body.brief.requirements.find(r=>r.id===imaging.id).matchIntent,'interest');
  assert.deepEqual(focus.body.brief.roles,['Cardiologist']);assert.equal(h.counts().searches,3);
});

test('API resumes short discovery with exact intent and rejects invented intent metadata',async t=>{
  const h=await harness(t),brief=parseBrief({message:'Cardiologists with research interests in imaging. Research is helpful.'}).brief;
  const resumed=await h.post('search',{resumeBrief:brief});assert.equal(resumed.status,200);assert.deepEqual(resumed.body.brief,brief);assert.equal(resumed.body.interpretationMode,'saved-brief');
  const invalid=structuredClone(brief);invalid.requirements.find(r=>r.kind==='modality').matchIntent='approved';
  assert.equal((await h.post('search',{resumeBrief:invalid})).status,400);assert.equal(h.counts().searches,1);
});
