'use strict';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const evidenceAnchor=id=>'evidence-'+id;
const {sourceLinks}=require('./public/evidence.js');
const labels={'clinical-interest':'Listed clinical interests','clinical-practice':'Documented clinical activity',research:'Research involvement',publication:'Publication evidence',trial:'Trial evidence',qualification:'Recorded qualifications',training:'Recorded training',teaching:'Teaching activity',affiliation:'Recorded affiliation',relationship:'Recorded relationship',location:'Practice location','activity-volume':'Reported activity volume',registration:'Registration record',biography:'Professional biography'};
const qualifications={historical:'This passage describes historical activity.','stated-interest':'A listed interest does not establish performed clinical activity.','research-interest-not-study-experience':'Research interest is not evidence of conducting or evaluating a study.','bibliographic-reference-not-training-or-authorship':'A bibliographic reference does not establish training or authorship.','publication-listing-link-not-authorship':'A publication-profile link does not verify individual publications or authorship.','legal-work-not-clinical-care':'Medico-legal work does not establish clinical care.','training-not-practice':'Training does not establish current practice.','reported-current-practice':'The source reports current practice; confirm its date and present relevance.','contains-negation':'Read negative statements in context before relying on this passage.','relationship-not-conflict-determination':'A recorded relationship is not a conflict-of-interest determination.','self-reported-activity':'Reported activity has not been independently counted.','recorded-location-not-residence-or-current-practice':'A listed location does not establish residence or current practice.'};
function originalLinks(p){
  return sourceLinks(p);
}
function renderSourcePage(candidate,facts,selected){
  const article=(p,isSelected=false)=>{
    const links=originalLinks(p),limits=[...(p.review?.limitations||[]),...(p.qualifiers||[]).map(v=>qualifications[v]||String(v).replace(/-/g,' '))].filter(v=>typeof v==='string'&&v.trim());
    return `<article id="${escape(evidenceAnchor(p.id))}"${isSelected?' class="cited-passage"':''} style="scroll-margin-top:24px">${isSelected?'<p class="eyebrow">Cited passage</p>':''}<h2>${escape(labels[p.type]||'Professional source evidence')}</h2><p>${escape(p.sourceLabel||'Stored professional record')}</p>${p.reviewedParaphrase?`<p><strong>Reviewed source summary</strong></p><p>${escape(p.text)}</p>${p.sourceQuote?`<p><strong>Exact source excerpt</strong></p><blockquote>${escape(p.sourceQuote)}</blockquote>`:'<p>No literal excerpt was recorded; this is a reviewed summary.</p>'}`:`<blockquote>${escape(p.text)}</blockquote>`}<p>Source date: ${escape(p.dates?.sourceDate||'Not recorded')}. ${p.dates?.sourceDate?'A recorded date does not by itself confirm current practice.':'Current practice cannot be dated from this record.'}</p>${limits.length?`<p><strong>Evidence qualifications</strong></p><ul>${[...new Set(limits)].map(v=>`<li>${escape(v)}</li>`).join('')}</ul>`:''}${links.length?links.map(link=>`<p><a href="${escape(link.url)}" rel="noopener noreferrer" target="_blank">${escape(link.label)} ↗</a></p>`).join(''):'<p>Original page link unavailable. This quotation comes from the stored record.</p>'}<details><summary>Record details</summary><p>Evidence identifier: ${escape(p.id)}<br>Stored source record: ${escape(p.sourceRecordId)}<br>Source field: ${escape(p.field)}<br>Attribution: ${escape(p.attribution||'Stored source record')}<br>Retrieved or checked: ${escape(p.dates?.observedAt||'Not recorded')}<br>Database processing date: ${escape(p.dates?.mergeDate||'Not recorded')}</p>${links.flatMap(link=>link.provenance.map(source=>`<p>Additional provenance: <a href="${escape(link.url)}" rel="noopener noreferrer" target="_blank">${escape(source.sourceLabel)}</a><br>Stored source record: ${escape(source.sourceRecordId||'Not recorded')} · field: ${escape(source.field||'Not recorded')}<br>Source date: ${escape(source.dates?.sourceDate||'Not recorded')} · Retrieved or checked: ${escape(source.dates?.observedAt||'Not recorded')}<br>Database processing date: ${escape(source.dates?.mergeDate||'Not recorded')} · Attribution: ${escape(source.attribution)}</p>`)).join('')}<p>Retrieval and database processing dates describe record handling, not when clinical practice occurred.</p></details></article>`;
  };
  const rest=selected?facts.filter(p=>p.id!==selected.id):facts;
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(candidate.name)} — stored source evidence</title><link rel="stylesheet" href="/expert-assets/styles.css"><body class="source-page"><main><a href="/expert-discovery">DocMap Expert Discovery</a><h1>${escape(candidate.name)}</h1><p>Stored professional evidence. These records do not establish current registration, availability, independence or assessment approval.</p>${selected?article(selected,true):''}${selected&&rest.length?'<h2>Other stored evidence for this professional</h2>':''}${rest.map(p=>article(p)).join('')}</main></body></html>`;
}
module.exports={renderSourcePage,evidenceAnchor,originalLinks};
