'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {Client}=require('pg'),{migrate}=require('../db.cjs'),U=require('../util.cjs'),{fixture}=require('./fixture.cjs'),I=require('../importer.cjs'),R=require('../reader.cjs');
test('isolated PostgreSQL: atomic import, parity, approvals, historical citations and rollback',async t=>{
  const file=process.env.DOCMAP_DB_CONNECTION_FILE;if(!file)throw Error('Tests require a dedicated local PostgreSQL connection');const config=await U.json(file);assert.equal(config.host,'127.0.0.1');
  const admin=new Client({...config,database:'postgres'});await admin.connect();const name='docmap_db_test_'+process.pid;await admin.query(`create database ${name}`);
  const db=new Client({...config,database:name});await db.connect();const root=path.resolve(__dirname,'../.private/tests-'+Date.now());await fs.mkdir(root,{recursive:true});
  try{await migrate(db);await migrate(db);const a=await fixture(root,'test-db-a'),b=await fixture(root,'test-db-b',{wording:'MR reporting; CT training only.'});
    await t.test('interrupted imports expose no rows or release',async()=>{await assert.rejects(I.importRelease(db,{...a,reportFile:path.join(root,'interrupted.ndjson'),failAfter:5}),/Injected/);assert.equal((await db.query('select count(*)::int n from docmap_professional.records')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from docmap_professional.releases')).rows[0].n,0);});
    await t.test('restricted importer preserves meaning and cannot publish; repeats are idempotent',async()=>{const notices=[];const notice=n=>notices.push(n);db.on('notice',notice);await db.query('set role docmap_professional_importer');try{const rights=(await db.query("select has_table_privilege(current_user,'docmap_professional.evidence','MAINTAIN') maintenance,has_table_privilege(current_user,'docmap_professional.publication_events','INSERT') publication")).rows[0];assert.deepEqual(rights,{maintenance:true,publication:false});const summary=await I.importRelease(db,{...a,reportFile:path.join(root,'a.ndjson')});assert.equal(summary.passed,true);assert.equal((await I.importRelease(db,{...a,reportFile:path.join(root,'repeat.ndjson')})).idempotent,true);assert.ok(!notices.some(n=>/skipping|permission|privilege/i.test(n.message)));}finally{await db.query('reset role');db.removeListener('notice',notice);}const got=await R.loadCorpus(db,a.pin,{staging:true});assert.deepEqual(got.corpus.passages,a.corpus.passages);assert.deepEqual(got.corpus.candidates,a.corpus.candidates);assert.deepEqual(got.corpus.identityLedger,a.corpus.identityLedger);const rows=await R.loadRows(db,a.pin,{staging:true});assert.ok(!rows.rows.find(x=>x.id==='fixture_ct').email);assert.equal(got.corpus.passages.find(x=>x.volume?.reportedRange==='<=7').volume.countNumeric,null);assert.equal(got.corpus.passages.find(x=>x.volume?.reportedRange==='<=7').volume.reportingPeriod,null);assert.ok(got.corpus.candidates.some(c=>c.registrations.some(r=>r.body==='HCPC')));});
    await t.test('unapproved, missing, wrong hash and incompatible releases fail readiness',async()=>{await assert.rejects(R.loadCorpus(db,a.pin),/approval/);await assert.rejects(R.loadCorpus(db,{...a.pin,releaseId:'missing'}),/unavailable/);await assert.rejects(R.loadCorpus(db,{...a.pin,manifestSha256:'f'.repeat(64)},{staging:true}),/corrupt/);await assert.rejects(R.loadCorpus(db,{...a.pin,corpusVersion:'unsupported'},{staging:true}),/incompatible/);});
    await t.test('release profiles use the exact frozen projection and omit identity holds',async()=>{const file=path.join(root,'profiles.ndjson'),descriptor=await require('../profiles.cjs').prepareProfiles(db,a.pin,{outputFile:file,staging:true}),expected=a.corpus.candidates.filter(c=>!c.needsIdentityReview);assert.equal(descriptor.profiles,expected.length);let n=0;for await(const item of require('../prepare.cjs').lines(file)){const c=expected[n++];assert.equal(item.candidateId,c.id);assert.deepEqual(item.profile,require(path.join(a.binding.runtimeDir,'expert/profile.cjs')).buildProfile(c,a.corpus.passages.filter(p=>p.candidateId===c.id),{corpusVersion:a.pin.corpusVersion,dataReleaseId:a.pin.releaseId}));}assert.equal(n,expected.length);});
    await t.test('sealed releases and old decisions cannot be overwritten or extended',async()=>{await assert.rejects(db.query("update docmap_professional.records set projected='{}'"),/immutable/);await assert.rejects(db.query("delete from docmap_professional.dispositions"),/immutable/);await assert.rejects(U.insertBatch(db,'records',[{release_id:a.pin.releaseId,ordinal:999,record_id:'other',original_sha256:U.hash({}),projected_sha256:U.hash({}),original:{},projected:{},projected_json:'{}'}]),/sealed/);});
    await t.test('private archive links rehash original bytes and roll back invalid references',async()=>{const A=require('../archives.cjs'),archiveRoot=path.join(root,'archive');await fs.mkdir(archiveRoot);const bytes=Buffer.from('<html>CT MR source fixture</html>'),sourceFile=path.join(archiveRoot,'source.html');await fs.writeFile(sourceFile,bytes);const manifestFile=path.join(archiveRoot,'backup-manifest.json');await fs.writeFile(manifestFile,JSON.stringify({files:[{path:'source.html',sha256:U.sha(bytes),bytes:bytes.length}]}));const catalogFile=path.join(root,'archive-catalog.json'),receipt=await A.verifyArchiveCatalog({root:archiveRoot,manifestFile,manifestSha256:await U.fileHash(manifestFile),outputFile:catalogFile});await A.registerArchives(db,{catalogFile,catalogSha256:receipt.catalogSha256});await A.registerArchives(db,{catalogFile,catalogSha256:receipt.catalogSha256});assert.equal((await db.query('select count(*)::int n from docmap_professional.archive_links')).rows[0].n,1);await fs.appendFile(sourceFile,'changed');await assert.rejects(A.registerArchives(db,{catalogFile,catalogSha256:receipt.catalogSha256}),/hash mismatch/);assert.equal((await db.query('select count(*)::int n from docmap_professional.archive_links')).rows[0].n,1);});
    await t.test('reader role cannot access originals; staged evidence remains inaccessible',async()=>{await db.query('set role docmap_professional_reader');try{assert.equal((await db.query('select count(*)::int n from docmap_professional.evidence')).rows[0].n,0);await assert.rejects(db.query('select * from docmap_professional.records'),/permission denied/);}finally{await db.query('reset role');}});
    await t.test('compatible approved test releases switch without rewriting citations or saves',async()=>{
      await I.importRelease(db,{...b,reportFile:path.join(root,'b.ndjson')});
      for(const f of [a,b]){const r=(await db.query('select * from docmap_professional.releases where release_id=$1',[f.pin.releaseId])).rows[0];const receipt={schemaVersion:1,eventId:'approval-'+f.pin.releaseId,releaseId:f.pin.releaseId,decision:'approved',manifestSha256:r.manifest_sha256,corpusSha256:r.corpus_sha256,corpusVersion:r.corpus_version,projectionVersion:r.projection_version,safetySha256:r.safety_sha256,authority:'main-validation-human-approval',approvalReference:'SYNTHETIC TEST ONLY; no approval of a real package'};const receiptFile=path.join(f.dir,'approval.json');await fs.writeFile(receiptFile,JSON.stringify(receipt));f.pin.approvalSha256=U.hash(receipt);await R.publish(db,{receiptFile,receiptSha256:f.pin.approvalSha256});}
      assert.equal((await R.compatibleSelection(db,a.pin,b.pin)).compatible,true);
      const saved=structuredClone(a.corpus.passages[0]),savedHash=U.hash(saved),S=require('../saved-evidence.cjs'),envelope=await S.capture(db,a.pin,{candidateId:saved.candidateId,evidenceIds:[saved.id]}),cacheKey=S.explanationCacheKey(envelope.snapshot,{model:'deepseek/deepseek-v3.2',runtimeSha256:U.hash('runtime'),promptSha256:U.hash('prompt')});await R.loadCorpus(db,b.pin);const citation=await R.historicalCitation(db,a.pin,{candidateId:saved.candidateId,evidenceId:saved.id});assert.equal(citation.status,200);assert.deepEqual(citation.evidence,saved);await R.loadCorpus(db,a.pin);assert.equal(U.hash(saved),savedHash);assert.deepEqual(S.restore(envelope).evidence,[saved]);assert.equal(S.explanationCacheKey(S.restore(envelope),{model:'deepseek/deepseek-v3.2',runtimeSha256:U.hash('runtime'),promptSha256:U.hash('prompt')}),cacheKey);assert.equal((await R.historicalCitation(db,{...a.pin,releaseId:'missing'},{candidateId:saved.candidateId,evidenceId:saved.id})).status,410);
      await db.query('set role docmap_professional_reader');try{assert.ok((await db.query('select count(*)::int n from docmap_professional.evidence')).rows[0].n>0);assert.deepEqual((await R.loadCorpus(db,a.pin)).corpus.passages,a.corpus.passages);}finally{await db.query('reset role');}
      const corruptSerialization={query:async(sql,params)=>sql.startsWith('select e.payload_json')?{rows:[{payload_json:'{invalid-json',payload_sha256:savedHash,payload:saved,held:false}]}:db.query(sql,params)};assert.equal((await R.historicalCitation(corruptSerialization,a.pin,{candidateId:saved.candidateId,evidenceId:saved.id})).status,410);
      const P=require(path.join(a.binding.runtimeDir,'expert/public/projects.js')),J=await require('../projects-adapter.cjs').createProjectAdapter({runtimeRoot:a.binding.runtimeDir,runtimeManifestSha256:a.manifest.runtimeManifestSha256}),brief={version:1,summary:'Saved source evidence',requirements:[]},candidate={...a.corpus.candidates.find(c=>c.id===saved.candidateId),evidence:[saved],requirementMatrix:[],reasons:[]};let project=P.saveCandidate(P.createProject('Database rollback rehearsal'),candidate,brief,a.pin.corpusVersion,{dataReleaseId:a.pin.releaseId});project=await J.attach(db,a.pin,project,{candidateId:saved.candidateId,evidenceIds:[saved.id]});project=J.changeReview(project,saved.candidateId,'qualification','reviewed-by-team',{actor:'user'});const restored=J.importJSON(J.exportJSON(project));assert.deepEqual(restored.candidates,project.candidates);assert.ok(J.exportHTML(project).includes(a.pin.manifestSha256));assert.equal(J.selectionStatus(project,{...envelope.snapshot.versions,dataReleaseId:b.pin.releaseId})[0].requiresReview,true);assert.equal(project.candidates[0].qualification,'reviewed-by-team');assert.equal(project.candidates[0].databaseVersions.projectionVersion,'expert-repair-v2');
    });
    await t.test('same-transaction revocation wins under the restricted publisher and reader roles',async()=>{const r=(await db.query('select * from docmap_professional.releases where release_id=$1',[b.pin.releaseId])).rows[0],base={schemaVersion:1,releaseId:b.pin.releaseId,manifestSha256:r.manifest_sha256,corpusSha256:r.corpus_sha256,corpusVersion:r.corpus_version,projectionVersion:r.projection_version,safetySha256:r.safety_sha256,authority:'main-validation-human-approval',approvalReference:'SYNTHETIC TEST ONLY'};await db.query('set role docmap_professional_publisher');await db.query('begin');let approvedSha;try{for(const [eventId,decision]of [['zz-approval','approved'],['aa-revocation','revoked']]){const receipt={...base,eventId,decision},receiptFile=path.join(root,eventId+'.json');await fs.writeFile(receiptFile,JSON.stringify(receipt));await R.publish(db,{receiptFile,receiptSha256:U.hash(receipt)});if(decision==='approved')approvedSha=U.hash(receipt);}await db.query('commit');}catch(e){await db.query('rollback');throw e;}finally{await db.query('reset role');}const events=(await db.query("select created_at,decision from docmap_professional.publication_events where event_id in ('zz-approval','aa-revocation') order by publication_order")).rows;assert.equal(events[0].created_at.getTime(),events[1].created_at.getTime());assert.equal(events[1].decision,'revoked');await assert.rejects(R.release(db,{...b.pin,approvalSha256:approvedSha}),/approval/);await db.query('set role docmap_professional_reader');try{assert.equal((await db.query('select count(*)::int n from docmap_professional.evidence where release_id=$1',[b.pin.releaseId])).rows[0].n,0);}finally{await db.query('reset role');}});
    await t.test('malformed, stale and duplicate corrections are rejected before import',async()=>{const bad=await fixture(root,'test-db-duplicate',{duplicate:true});await assert.rejects(I.preflight(bad.bindingFile,bad.bindingSha256),/duplicate/i);assert.throws(()=>I.provenance({sourceUrl:'javascript:alert(1)'}),/Unsafe/);assert.throws(()=>U.date('2026-02-30'),/calendar/);assert.throws(()=>U.date('2026'),/date/);const blob=await fs.readFile(a.binding.manifestPath);await fs.appendFile(a.binding.manifestPath,' ');await assert.rejects(I.preflight(a.bindingFile,a.bindingSha256),/hash mismatch/);await fs.writeFile(a.binding.manifestPath,blob);});
  }finally{await db.end();await admin.query(`drop database ${name}`);await admin.end();}
});
