'use strict';
// Private archive verification never publishes raw HTML or assigns observation dates.
const path=require('node:path'),fs=require('node:fs/promises'),U=require('./util.cjs');
async function verifyArchiveCatalog({root,manifestFile,manifestSha256,outputFile,selectedNames=null}){
  if(!path.isAbsolute(root)||!path.isAbsolute(outputFile))throw Error('Absolute private archive paths required');await U.verify(manifestFile,manifestSha256);const manifest=await U.json(manifestFile),objects=[],seen=new Map();
  for(const item of manifest.files){if(!/\.html?$/i.test(item.path))continue;const key=item.path.replace(/\\/g,'/');const file=U.inside(root,key);let status='not-verified';if(!selectedNames||selectedNames.includes(path.posix.basename(key))){status='unavailable';try{await U.verify(file,item.sha256);if((await fs.stat(file)).size!==item.bytes)throw Error('Archive byte-count mismatch');status='verified-private-object';}catch(e){if(e.code!=='ENOENT'&&e.code!=='EACCES')throw e;}}const obj={objectKey:key,sha256:item.sha256,bytes:item.bytes,status,storage:'private-local-archive',sourceDate:null,observedAt:null};objects.push(obj);if(status==='verified-private-object')seen.set(item.sha256,obj);}
  const catalog={schemaVersion:1,format:'docmap-private-archive-catalog-v1',manifestSha256,root,objects};await fs.writeFile(outputFile,JSON.stringify(catalog,null,2),{flag:'wx'});return {objects:objects.length,verified:seen.size,unavailable:objects.filter(x=>x.status==='unavailable').length,notVerified:objects.filter(x=>x.status==='not-verified').length,catalogSha256:await U.fileHash(outputFile)};
}
async function registerArchives(db,{catalogFile,catalogSha256,onProgress=()=>{}}){
  await U.verify(catalogFile,catalogSha256);const catalog=await U.json(catalogFile);if(catalog.format!=='docmap-private-archive-catalog-v1')throw Error('Unsupported archive catalog');const objects=catalog.objects.filter(x=>x.status==='verified-private-object'),writer=U.batch(db,'archive_links');
  await db.query('begin');try{for(let i=0;i<objects.length;i+=8){const group=objects.slice(i,i+8),checked=await Promise.allSettled(group.map(async obj=>{const file=U.inside(catalog.root,obj.objectKey);await U.verify(file,obj.sha256);if((await fs.stat(file)).size!==obj.bytes)throw Error('Archive byte-count mismatch');return new Date().toISOString();}));for(const result of checked)if(result.status==='rejected')throw result.reason;for(let n=0;n<group.length;n++){const obj=group[n];await writer.push({content_sha256:obj.sha256,catalog_sha256:catalogSha256,object_key:obj.objectKey,byte_count:obj.bytes,verified_at:checked[n].value,descriptor:{storage:obj.storage,root:catalog.root,manifestSha256:catalog.manifestSha256,sourceDate:null,observedAt:null}});}if(i%2000===0)onProgress({verified:i+group.length,total:objects.length});}await writer.flush();await U.verify(catalogFile,catalogSha256);await db.query('commit');return {objects:objects.length,catalogSha256};}catch(e){await db.query('rollback');throw e;}
}
module.exports={verifyArchiveCatalog,registerArchives};
