'use strict';
const U=require('./util.cjs');
const OPS=new Set(['add','change','remove']),FIELDS=new Set(['about','clinical_interests','areas_of_interest','research_interests','professional_context']);
function validateProposal(packet){
  if(packet.schemaVersion!==1||packet.format!=='docmap-ingestion-proposal-v1'||!packet.proposalId||!packet.baseReleaseId||!Array.isArray(packet.sources)||!packet.sources.length||!Array.isArray(packet.changes)||!Array.isArray(packet.conflicts)||!Array.isArray(packet.quarantine)||!Array.isArray(packet.outcomes))throw Error('Incomplete pipeline proposal');
  const quarantined=c=>packet.quarantine.some(q=>q.recordId===c.recordId&&(q.scope==='whole-identity-hold'||q.sourceKey===c.sourceKey&&q.field===c.field&&(q.scope==='source-field-exclusion'||q.scope==='rejected-source-addition'&&c.operation==='add')));
  const sources=new Map();for(const s of packet.sources){if(!s.sourceKey||sources.has(s.sourceKey)||!s.provider||!s.providerRecordId||!s.version||!s.hashSemantics||!['original-bytes','canonical-source-record'].includes(s.hashSemantics)||!/^[a-f0-9]{64}$/.test(s.contentSha256||'')||!s.archive||!s.archive.private||!s.archive.objectKey||!s.archive.sha256||s.archive.sha256!==s.contentSha256||!Number.isSafeInteger(s.archive.bytes)||s.archive.bytes<1||!s.archive.mediaType||!Object.hasOwn(s,'sourceDate')||!Object.hasOwn(s,'observedAt'))throw Error('Unbound immutable source');U.safeUrl(s.requestedUrl);U.safeUrl(s.finalUrl);U.date(s.sourceDate);U.date(s.observedAt);sources.set(s.sourceKey,s);}
  const seen=new Set();for(const c of packet.changes){const s=sources.get(c.sourceKey),key=[c.recordId,c.field,c.sourceKey].join('|');if(!s||c.sourceVersion!==s.version||c.sourceSha256!==s.contentSha256||!OPS.has(c.operation)||!FIELDS.has(c.field)||!c.recordId||seen.has(key)||!c.ownership||!['corroborated-existing-owner','source-native-import-continuity','unresolved'].includes(c.ownership.decision)||!c.ownership.receiptSha256||!Array.isArray(c.boundaries)||!c.boundaries.length||!Array.isArray(c.qualifiers)||!c.parseOutcome||!c.attributionOutcome||!c.qualityOutcome)throw Error('Unsafe or conflicting field proposal');seen.add(key);if(c.operation!=='add'&&!/^[a-f0-9]{64}$/.test(c.beforeValueSha256||''))throw Error('Original-value hash required');if(c.operation==='remove'&&c.value!==null)throw Error('Removal must remain an explicit null proposal');for(const b of c.boundaries)if(b.originalField==null||!Number.isInteger(b.start)||!Number.isInteger(b.end)||b.start<0||b.end<=b.start||!/^[a-f0-9]{64}$/.test(b.exactSpanSha256||''))throw Error('Invalid original boundary');}
  const fields=new Map();for(const c of packet.changes){if(!/^[a-f0-9]{64}$/.test(c.ownership.receiptSha256)||!['parsed','partial','failed','invalid-encoding','schema-incompatible'].includes(c.parseOutcome)||!['owned','unresolved','conflicting'].includes(c.attributionOutcome)||!['eligible-for-review','quarantined','rejected'].includes(c.qualityOutcome))throw Error('Unreviewed pipeline outcome');if((c.ownership.decision==='unresolved'||c.attributionOutcome!=='owned'||c.parseOutcome!=='parsed')&&!quarantined(c))throw Error('Unresolved change lacks a matching explicit quarantine');for(const b of c.boundaries)if(!['utf8-bytes','unicode-codepoints','utf16-codeunits'].includes(b.offsetEncoding))throw Error('Boundary offset encoding required');const key=c.recordId+'|'+c.field,prior=fields.get(key);if(prior&&U.hash(prior.value)!==U.hash(c.value)&&!packet.conflicts.some(q=>q.recordId===c.recordId&&q.field===c.field&&Array.isArray(q.sourceKeys)&&q.sourceKeys.includes(prior.sourceKey)&&q.sourceKeys.includes(c.sourceKey)))throw Error('Conflicting source proposals lack explicit conflict');fields.set(key,c);}
  for(const s of packet.sources){if(s.archive.private!==true||typeof s.archive.objectKey!=='string'||s.archive.objectKey.split(/[\\/]/).some(k=>!k||k==='.'||k==='..')||s.archive.objectKey.startsWith('/')||/^[a-z]:/i.test(s.archive.objectKey))throw Error('Unsafe private object key');}
  for(const c of packet.changes){if(!Object.hasOwn(c,'value')||typeof c.evidenceType!=='string'||!c.evidenceType.trim()||!c.dates||!Object.hasOwn(c.dates,'sourceDate')||!Object.hasOwn(c.dates,'observedAt'))throw Error('Evidence type, value and explicit date semantics required');U.date(c.dates.sourceDate);U.date(c.dates.observedAt);if(c.qualityOutcome!=='eligible-for-review'&&!quarantined(c))throw Error('Rejected change lacks a matching explicit quarantine');}
  for(const q of packet.quarantine){if(!q.decisionId||!q.recordId||!q.reason||!['whole-identity-hold','source-field-exclusion','rejected-source-addition'].includes(q.scope)||q.scope!=='whole-identity-hold'&&(!sources.has(q.sourceKey)||!FIELDS.has(q.field)))throw Error('Unscoped quarantine decision');}
  for(const c of packet.conflicts){if(!c.recordId||!c.reason||!Array.isArray(c.sourceKeys)||new Set(c.sourceKeys).size<2||c.sourceKeys.some(k=>!sources.has(k))||!Array.isArray(c.assertions)||c.assertions.length<2)throw Error('Unbound unresolved conflict');}
  const outcomes=new Set();for(const o of packet.outcomes){if(!sources.has(o.sourceKey)||outcomes.has(o.sourceKey)||!['parsed','parsed-with-quarantine','failed','invalid-encoding','schema-incompatible','skipped','unavailable'].includes(o.status))throw Error('Invalid source accounting outcome');outcomes.add(o.sourceKey);}
  for(const s of packet.sources)if(!outcomes.has(s.sourceKey))throw Error('Source has no parse/accounting outcome');
  return packet;
}
async function stageProposal(db,packet){validateProposal(packet);const release=(await db.query('select release_id from docmap_professional.releases where release_id=$1',[packet.baseReleaseId])).rows[0];if(!release)throw Error('Unknown proposal base release');const digest=U.hash(packet),old=(await db.query('select proposal_sha256 from docmap_professional.proposals where proposal_id=$1',[packet.proposalId])).rows[0];if(old){if(old.proposal_sha256!==digest)throw Error('Proposal ID collision');return {idempotent:true};}await U.insertBatch(db,'proposals',[{proposal_id:packet.proposalId,base_release_id:packet.baseReleaseId,source_key:packet.sources.map(s=>s.sourceKey).join('|'),source_version_sha256:U.hash(packet.sources),proposal_sha256:digest,payload:packet}]);return {status:'proposed-private',proposalSha256:digest,invalidatedSourceKeys:packet.sources.map(s=>s.sourceKey),requiresNewReview:true};}
module.exports={validateProposal,stageProposal};
