'use strict';
// Local-only staging preview. Published product integration uses expert-adapter.cjs.
const http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const {connect}=require('./db.cjs'),R=require('./reader.cjs'),U=require('./util.cjs');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function createPreview({db,pin,staging=false}){
  const release=await R.release(db,pin,{staging}),runtime=await require('./runtime.cjs').verifyRuntime(release.binding.runtimeDir,release.manifest.runtimeManifestSha256),{BM25Index}=require(path.join(runtime,'expert/search.cjs')),{buildProfile,VERSION}=require(path.join(runtime,'expert/profile.cjs'));if(VERSION!==R.versions(release).profileVersion)throw Error('Profile runtime version differs from pin');
  const loaded=await R.loadSearchCorpus(db,pin,{staging}),corpus=loaded.corpus,index=new BM25Index(corpus.passages),owners=new Map(corpus.candidates.map(c=>[c.id,c])),versions=loaded.dataRelease;
  async function hit(x){const p=corpus.passages[x.index],result=await R.historicalCitation(db,pin,{candidateId:p.candidateId,evidenceId:p.id},{staging});if(result.status!==200)throw Error('Pinned evidence unavailable');return {score:x.score,evidence:result.evidence,candidate:owners.get(p.candidateId)};}
  const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");
    const send=(status,body)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body));};
    try{if(req.method!=='GET')return send(405,{error:'Read-only preview'});const url=new URL(req.url,'http://127.0.0.1');
      // Revalidate approval/revocation at each request, including warm caches.
      await R.release(db,pin,{staging});
      if(url.pathname==='/health')return send(200,{ready:true,status:loaded.status,retrieval:'BM25 staging diagnostic',...versions,counts:corpus.audit});
      if(url.pathname==='/api/search'){const query=url.searchParams.get('q')||'';if(query.length>500)return send(400,{error:'Query too long'});const hits=[];for(const x of index.search(query).slice(0,30))hits.push(await hit(x));return send(200,{...versions,mode:'BM25 staging diagnostic',hits});}
      if(url.pathname==='/api/profile'){const p=await R.profileEvidence(db,pin,url.searchParams.get('candidateId'),{staging});if(!p)return send(404,{error:'Professional unavailable'});return send(200,{...buildProfile(p.candidate,p.passages,{corpusVersion:corpus.version,dataReleaseId:pin.releaseId}),versions});}
      if(url.pathname==='/api/citation'){const result=await R.historicalCitation(db,{...pin,releaseId:url.searchParams.get('releaseId')||pin.releaseId},{candidateId:url.searchParams.get('candidateId'),evidenceId:url.searchParams.get('evidenceId')},{staging});return send(result.status,result);}
      if(url.pathname==='/api/export'){const p=await R.profileEvidence(db,pin,url.searchParams.get('candidateId'),{staging});if(!p)return send(404,{error:'Professional unavailable'});const evidence=p.passages,c=p.candidate;const envelope=await require('./saved-evidence.cjs').capture(db,pin,{candidateId:c.id,evidenceIds:evidence.slice(0,500).map(p=>p.id)},{staging});return send(200,{...envelope,versions,candidate:c,evidence,complete:evidence.length<=500});}
      if(url.pathname!=='/')return send(404,{error:'Unavailable'});const q=url.searchParams.get('q')||'';if(q.length>500)return send(400,{error:'Query too long'});const hits=[];for(const x of index.search(q).slice(0,12))hits.push(await hit(x));res.setHeader('Content-Type','text/html; charset=utf-8');res.end(`<!doctype html><meta name="viewport" content="width=device-width"><title>DocMap database preview</title><style>body{max-width:960px;margin:40px auto;padding:0 20px;font:17px system-ui;line-height:1.5}input{font:inherit;padding:8px;width:65%}button{font:inherit;padding:8px}article{border-top:1px solid #bbb;padding:20px 0}blockquote{margin-left:0;white-space:pre-wrap}small{overflow-wrap:anywhere}</style><h1>DocMap database preview</h1><p>${staging?'Staged release — publication approval pending.':'Pinned approved release.'} Search retrieves recorded passages with BM25. Results retain their source evidence types and limitations.</p><small>${escape(pin.releaseId)} · ${escape(pin.corpusVersion)}</small><form><p><input aria-label="Search professional evidence" name="q" value="${escape(q)}"><button>Search</button></p></form>${hits.map(x=>{const p=x.evidence,c=x.candidate,params=new URLSearchParams({candidateId:c.id,evidenceId:p.id,releaseId:pin.releaseId});return `<article><h2>${escape(c.name)}</h2><p>${escape(p.type)} · ${escape((p.qualifiers||[]).join(' · '))}</p><blockquote>${escape(p.text)}</blockquote><small>${escape(JSON.stringify(p.dates||{}))}</small><p><a href="/api/citation?${params}">Exact historical citation</a> · <a href="/api/profile?candidateId=${encodeURIComponent(c.id)}">Profile</a> · <a href="/api/export?candidateId=${encodeURIComponent(c.id)}">Export evidence</a></p></article>`;}).join('')}`);
    }catch{send(503,{ready:false,error:'Pinned release readiness failed'});}
  });return {server,corpus,index,versions};
}
if(require.main===module)(async()=>{const config=await U.json(process.env.DOCMAP_PREVIEW_CONFIG_FILE),db=await connect(),preview=await createPreview({db,pin:config.pin,staging:config.staging===true});preview.server.listen(config.port||55440,'127.0.0.1',()=>console.log(JSON.stringify({url:'http://127.0.0.1:'+(config.port||55440),status:config.staging?'staged-unapproved':'approved',releaseId:config.pin.releaseId})));process.on('SIGINT',()=>preview.server.close(async()=>{await db.end();process.exit();}));})().catch(e=>{console.error(e.message);process.exitCode=1;});
module.exports={createPreview};
