'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),R=require('./reader.cjs'),U=require('./util.cjs');
async function prepareProfiles(db,pin,{outputFile,staging=false}={}){
  if(!path.isAbsolute(outputFile||''))throw Error('Absolute private profile output required');const r=await R.release(db,pin,{staging}),runtime=r.binding.runtimeDir;
  await U.verify(path.join(runtime,'deployment-manifest.json'),r.manifest.runtimeManifestSha256);const manifest=await U.json(path.join(runtime,'deployment-manifest.json'));for(const f of manifest.files)await U.verify(U.inside(runtime,f.file),f.sha256);
  const {buildProfile,VERSION}=require(path.join(runtime,'expert/profile.cjs'));if(VERSION!==R.versions(r).profileVersion)throw Error('Profile projection version mismatch');
  const out=await fs.open(outputFile+'.pending','wx'),fingerprint=crypto.createHash('sha256'),started=Date.now();let count=0,held=0;
  try{for await(const candidate of R.items(db,r,'members')){if(candidate.needsIdentityReview){held++;continue;}const loaded=await R.profileEvidence(db,pin,candidate.id,{staging});if(!loaded)throw Error('Eligible professional became unavailable');const profile=buildProfile(candidate,loaded.passages,{corpusVersion:pin.corpusVersion,dataReleaseId:pin.releaseId});if(!profile)throw Error('Eligible professional lacks a profile');const bytes=Buffer.from(JSON.stringify({candidateId:candidate.id,profile,payloadSha256:U.hash(profile),versions:R.versions(r)})+'\n');let at=0;while(at<bytes.length){const written=await out.write(bytes,at,bytes.length-at);if(!written.bytesWritten)throw Error('Incomplete profile write');at+=written.bytesWritten;}fingerprint.update(bytes);count++;}await R.release(db,pin,{staging});await out.sync();}catch(e){await out.close();await fs.rename(outputFile+'.pending',outputFile+'.failed');throw e;}await out.close();await fs.rename(outputFile+'.pending',outputFile);
  const descriptor={format:'docmap-profiles-ndjson-v1',versions:R.versions(r),runtimeManifestSha256:r.manifest.runtimeManifestSha256,profileVersion:VERSION,profiles:count,heldExcluded:held,sha256:fingerprint.digest('hex'),milliseconds:Date.now()-started,staging};if(await U.fileHash(outputFile)!==descriptor.sha256)throw Error('Profile artifact hash mismatch');await db.query('insert into docmap_professional.derived_artifacts(release_id,kind,artifact_sha256,descriptor) values ($1,$2,$3,$4) on conflict do nothing',[pin.releaseId,staging?'profiles-staging-diagnostic':'profiles',descriptor.sha256,{...descriptor,file:outputFile}]);await fs.writeFile(outputFile+'.summary.json',JSON.stringify(descriptor,null,2),{flag:'wx'});return descriptor;
}
module.exports={prepareProfiles};
